In [109]:
import pandas as pd

temp = pd.read_csv("stage3.csv")

In [110]:
temp1 = temp.dropna(subset = "gun_type")

In [111]:
#Organzied by State and time

temp2 = temp1.sort_values(by=['state', "date"])

temp3 = temp2.drop(columns=["incident_url", "address", "source_url", "incident_url_fields_missing", "incident_characteristics", "latitude", "location_description", "longitude", "notes", "sources", "state_house_district",
            "state_senate_district", "participant_name"])

In [112]:
temp3.head(n=5)

,incident_id,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_stolen,gun_type,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type
465,92453,2014-01-01,Alabama,Huntsville,0,2,5.0,0::Unknown,0::Unknown,1.0,0::17,0::Teen 12-17||1::Adult 18+,0::Male||1::Male,NaN,0::Injured||1::Injured,0::Victim||1::Victim||2::Subject-Suspect
959,93118,2014-01-05,Alabama,Somerville,1,0,5.0,0::Unknown,0::Unknown,1.0,NaN,0::Adult 18+||1::Adult 18+,0::Female||1::Female,1::Family,"0::Killed||1::Unharmed, Arrested",0::Victim||1::Subject-Suspect
1046,93760,2014-01-06,Alabama,Mobile,0,0,1.0,0::Unknown||1::Unknown,0::Unknown||1::Unknown,2.0,6::16||7::16,6::Teen 12-17||7::Teen 12-17,6::Male||7::Male,NaN,0::Unharmed||1::Unharmed||2::Unharmed||3::Unha...,0::Victim||1::Victim||2::Victim||3::Victim||4:...
1986,95867,2014-01-13,Alabama,Marion,0,1,7.0,0::Unknown,0::Unknown,1.0,0::39,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Male||1::Male||2::Female,NaN,0::Injured||1::Unharmed||2::Unharmed,0::Victim||1::Subject-Suspect||2::Subject-Suspect
2237,97507,2014-01-14,Alabama,Talladega,0,1,3.0,0::Unknown,0::Unknown,1.0,0::9,0::Child 0-11,0::Male,NaN,0::Injured,0::Victim

In [113]:
## Checking the data type of columns

temp3.dtypes

temp3.info(verbose=True)

##  re-indexing the dataframe

temp4 = temp3.reset_index(drop=True)

temp4.head(n=5)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 140226 entries, 465 to 239153
Data columns (total 16 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   incident_id               140226 non-null  int64
 1   date                      140226 non-null  object
 2   state                     140226 non-null  object
 3   city_or_county            140226 non-null  object
 4   n_killed                  140226 non-null  int64
 5   n_injured                 140226 non-null  int64
 6   congressional_district    128301 non-null  float64
 7   gun_stolen                140179 non-null  object
 8   gun_type                  140226 non-null  object
 9   n_guns_involved           140226 non-null  float64
 10  participant_age           91195 non-null   object
 11  participant_age_group     115234 non-null  object
 12  participant_gender        118579 non-null  object
 13  participant_relationship  11661 non-null   object
 14  participant_status        123660 non-null  object
 15  participant_type          124655 non-null  object
dtypes: float64(2), int64(3), object(11)
memory usage: 18.2+ MB

,incident_id,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_stolen,gun_type,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type
0,92453,2014-01-01,Alabama,Huntsville,0,2,5.0,0::Unknown,0::Unknown,1.0,0::17,0::Teen 12-17||1::Adult 18+,0::Male||1::Male,NaN,0::Injured||1::Injured,0::Victim||1::Victim||2::Subject-Suspect
1,93118,2014-01-05,Alabama,Somerville,1,0,5.0,0::Unknown,0::Unknown,1.0,NaN,0::Adult 18+||1::Adult 18+,0::Female||1::Female,1::Family,"0::Killed||1::Unharmed, Arrested",0::Victim||1::Subject-Suspect
2,93760,2014-01-06,Alabama,Mobile,0,0,1.0,0::Unknown||1::Unknown,0::Unknown||1::Unknown,2.0,6::16||7::16,6::Teen 12-17||7::Teen 12-17,6::Male||7::Male,NaN,0::Unharmed||1::Unharmed||2::Unharmed||3::Unha...,0::Victim||1::Victim||2::Victim||3::Victim||4:...
3,95867,2014-01-13,Alabama,Marion,0,1,7.0,0::Unknown,0::Unknown,1.0,0::39,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Male||1::Male||2::Female,NaN,0::Injured||1::Unharmed||2::Unharmed,0::Victim||1::Subject-Suspect||2::Subject-Suspect
4,97507,2014-01-14,Alabama,Talladega,0,1,3.0,0::Unknown,0::Unknown,1.0,0::9,0::Child 0-11,0::Male,NaN,0::Injured,0::Victim

In [114]:
# ## Note gun_stolen column values is a string, but with inner and outer separators, according to James' Gun Violence data repo

## But let's make sure that it is in a string format

temp5 = temp4.astype({'gun_stolen':str})

## Now create a function to take care of || and :: ....

text_list = [] 
def extract(x):
    """This is a recursive function to extract text separated by ||"""
    ch = '|'
    if ch not in x:
        for i in range(len(x)):
            if x[i] == ":" and x[i+1] == ":":
                text = x[i+2:]
                text_list.append(text)
                return text_list
    else:
        for i in range(len(x)):
            if x[i] == '|' and x[i+1] == '|':
                first_text = x[0:i]
                for j in range(len(first_text)):
                    if first_text[j] == ":" and first_text[j+1] == ":":
                        better_text = first_text[j+2:]
                        text_list.append(better_text)
                        break
                newtext = x[i+2:]
                extract(newtext)
                break
        return text_list

In [115]:
## Now apply extract function to gun_stolen column

# for i in range(len(temp5)):
#     stats = temp5.loc[i, 'gun_stolen']
#     text_list = []
#     complete_list = extract(stats)
#     if not complete_list:
#         complete_list = ["NA"]
#         temp5.at[i, 'gun_stolen'] = complete_list
#     else:
#         counts = {}
#         for i in complete_list:
#             counts[i] = counts.get(i, 0) + 1
#         temp5.at[i, 'gun_stolen'] = counts

for i in range(len(temp5)):
    stats = temp5.loc[i, 'gun_stolen']
    text_list = []
    complete_list = extract(stats)
    temp5.at[i, 'gun_stolen'] = complete_list

In [116]:
temp5.head(5)

,incident_id,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_stolen,gun_type,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type
0,92453,2014-01-01,Alabama,Huntsville,0,2,5.0,[Unknown],0::Unknown,1.0,0::17,0::Teen 12-17||1::Adult 18+,0::Male||1::Male,NaN,0::Injured||1::Injured,0::Victim||1::Victim||2::Subject-Suspect
1,93118,2014-01-05,Alabama,Somerville,1,0,5.0,[Unknown],0::Unknown,1.0,NaN,0::Adult 18+||1::Adult 18+,0::Female||1::Female,1::Family,"0::Killed||1::Unharmed, Arrested",0::Victim||1::Subject-Suspect
2,93760,2014-01-06,Alabama,Mobile,0,0,1.0,"[Unknown, Unknown]",0::Unknown||1::Unknown,2.0,6::16||7::16,6::Teen 12-17||7::Teen 12-17,6::Male||7::Male,NaN,0::Unharmed||1::Unharmed||2::Unharmed||3::Unha...,0::Victim||1::Victim||2::Victim||3::Victim||4:...
3,95867,2014-01-13,Alabama,Marion,0,1,7.0,[Unknown],0::Unknown,1.0,0::39,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Male||1::Male||2::Female,NaN,0::Injured||1::Unharmed||2::Unharmed,0::Victim||1::Subject-Suspect||2::Subject-Suspect
4,97507,2014-01-14,Alabama,Talladega,0,1,3.0,[Unknown],0::Unknown,1.0,0::9,0::Child 0-11,0::Male,NaN,0::Injured,0::Victim

In [117]:
temp5.tail(5)

,incident_id,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_stolen,gun_type,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type
140221,1073419,2018-03-18,Wyoming,Casper,1,0,0.0,[Unknown],0::Unknown,1.0,0::49,0::Adult 18+,0::Male,NaN,0::Killed,0::Victim
140222,1076613,2018-03-19,Wyoming,Cheyenne,1,0,0.0,[Unknown],0::Unknown,1.0,NaN,0::Adult 18+,0::Male,NaN,0::Killed,0::Subject-Suspect
140223,1074675,2018-03-21,Wyoming,Casper,0,0,0.0,[Unknown],0::Unknown,1.0,0::20||1::22,0::Adult 18+||1::Adult 18+,0::Male||1::Male,NaN,"0::Unharmed, Arrested||1::Unharmed, Arrested",0::Subject-Suspect||1::Subject-Suspect
140224,1076607,2018-03-22,Wyoming,Glenrock,1,0,0.0,"[Unknown, Unknown]",0::Handgun||1::Rifle,2.0,0::86,0::Adult 18+,0::Male,NaN,0::Killed,0::Subject-Suspect
140225,1079998,2018-03-28,Wyoming,Jackson (Jackson Hole),0,0,0.0,[Stolen],0::Rifle,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
temp5.to_csv("temp5.csv")

In [119]:
maximum = 0
for i in range(len(temp5)):
    l = temp5.loc[i, 'gun_stolen']
    if not l:
        l = ["Unknown"]
        temp5.at[i, 'gun_stolen'] = l
    elif len(l) > maximum:
        maximum = len(l)
        print(f"This index {i} is the max so far with {maximum}")

This index 0 is the max so far with 1
This index 2 is the max so far with 2
This index 38 is the max so far with 4
This index 114 is the max so far with 7
This index 146 is the max so far with 8
This index 180 is the max so far with 13
This index 236 is the max so far with 35
This index 1112 is the max so far with 39
This index 1170 is the max so far with 41
This index 1248 is the max so far with 50
This index 4059 is the max so far with 100
This index 7628 is the max so far with 400

In [120]:
# Let's expand the dataframe to include three more columns

temp5[["Number_Unknown_Guns", "Number_Stolen_Guns", "Number_Not_Stolen_Guns"]] = None

In [121]:
temp5.head(5)

,incident_id,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_stolen,gun_type,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type,Number_Unknown_Guns,Number_Stolen_Guns,Number_Not_Stolen_Guns
0,92453,2014-01-01,Alabama,Huntsville,0,2,5.0,[Unknown],0::Unknown,1.0,0::17,0::Teen 12-17||1::Adult 18+,0::Male||1::Male,NaN,0::Injured||1::Injured,0::Victim||1::Victim||2::Subject-Suspect,None,None,None
1,93118,2014-01-05,Alabama,Somerville,1,0,5.0,[Unknown],0::Unknown,1.0,NaN,0::Adult 18+||1::Adult 18+,0::Female||1::Female,1::Family,"0::Killed||1::Unharmed, Arrested",0::Victim||1::Subject-Suspect,None,None,None
2,93760,2014-01-06,Alabama,Mobile,0,0,1.0,"[Unknown, Unknown]",0::Unknown||1::Unknown,2.0,6::16||7::16,6::Teen 12-17||7::Teen 12-17,6::Male||7::Male,NaN,0::Unharmed||1::Unharmed||2::Unharmed||3::Unha...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,None,None,None
3,95867,2014-01-13,Alabama,Marion,0,1,7.0,[Unknown],0::Unknown,1.0,0::39,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Male||1::Male||2::Female,NaN,0::Injured||1::Unharmed||2::Unharmed,0::Victim||1::Subject-Suspect||2::Subject-Suspect,None,None,None
4,97507,2014-01-14,Alabama,Talladega,0,1,3.0,[Unknown],0::Unknown,1.0,0::9,0::Child 0-11,0::Male,NaN,0::Injured,0::Victim,None,None,None

In [122]:
# Rearranging the columns so the newly added columns are next to gun_stolen

temp6 = temp5[['incident_id', 'date', 'state', 'city_or_county', 'n_killed', 'n_injured', 'congressional_district', 'gun_stolen', 
'Number_Unknown_Guns', 'Number_Stolen_Guns', 'Number_Not_Stolen_Guns', 'gun_type', 'n_guns_involved', 'participant_age', 'participant_age_group', 
'participant_gender', 'participant_relationship', 'participant_status', 'participant_type']]

In [123]:
# Let's create a dictionary of items in gun_stolen and count them. Then put appropriate numbers in appropriate columns
for i in range(len(temp6)):
    gunstolen_list = temp6.loc[i, 'gun_stolen']
    gunstolen_dict = {}
    for j in gunstolen_list:
        gunstolen_dict[j] = gunstolen_dict.get(j, 0) + 1
    temp6.at[i, 'Number_Unknown_Guns'] = gunstolen_dict.get('Unknown')
    temp6.at[i, 'Number_Stolen_Guns'] = gunstolen_dict.get('Stolen')
    temp6.at[i, 'Number_Not_Stolen_Guns'] = gunstolen_dict.get('Not-Stolen')

In [124]:
stats = temp6.loc[7628, 'gun_stolen']

print(stats)


counts = {}
for i in stats:
    counts[i] = counts.get(i, 0) + 1
print(counts)

unk = counts.get('Unknown')
print(unk)

['Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown']
{'Unknown': 400}
400

In [125]:
temp6.head(5)

,incident_id,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_stolen,Number_Unknown_Guns,Number_Stolen_Guns,Number_Not_Stolen_Guns,gun_type,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type
0,92453,2014-01-01,Alabama,Huntsville,0,2,5.0,[Unknown],1,None,None,0::Unknown,1.0,0::17,0::Teen 12-17||1::Adult 18+,0::Male||1::Male,NaN,0::Injured||1::Injured,0::Victim||1::Victim||2::Subject-Suspect
1,93118,2014-01-05,Alabama,Somerville,1,0,5.0,[Unknown],1,None,None,0::Unknown,1.0,NaN,0::Adult 18+||1::Adult 18+,0::Female||1::Female,1::Family,"0::Killed||1::Unharmed, Arrested",0::Victim||1::Subject-Suspect
2,93760,2014-01-06,Alabama,Mobile,0,0,1.0,"[Unknown, Unknown]",2,None,None,0::Unknown||1::Unknown,2.0,6::16||7::16,6::Teen 12-17||7::Teen 12-17,6::Male||7::Male,NaN,0::Unharmed||1::Unharmed||2::Unharmed||3::Unha...,0::Victim||1::Victim||2::Victim||3::Victim||4:...
3,95867,2014-01-13,Alabama,Marion,0,1,7.0,[Unknown],1,None,None,0::Unknown,1.0,0::39,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Male||1::Male||2::Female,NaN,0::Injured||1::Unharmed||2::Unharmed,0::Victim||1::Subject-Suspect||2::Subject-Suspect
4,97507,2014-01-14,Alabama,Talladega,0,1,3.0,[Unknown],1,None,None,0::Unknown,1.0,0::9,0::Child 0-11,0::Male,NaN,0::Injured,0::Victim

In [126]:
temp6.tail(5)

,incident_id,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_stolen,Number_Unknown_Guns,Number_Stolen_Guns,Number_Not_Stolen_Guns,gun_type,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type
140221,1073419,2018-03-18,Wyoming,Casper,1,0,0.0,[Unknown],1,None,None,0::Unknown,1.0,0::49,0::Adult 18+,0::Male,NaN,0::Killed,0::Victim
140222,1076613,2018-03-19,Wyoming,Cheyenne,1,0,0.0,[Unknown],1,None,None,0::Unknown,1.0,NaN,0::Adult 18+,0::Male,NaN,0::Killed,0::Subject-Suspect
140223,1074675,2018-03-21,Wyoming,Casper,0,0,0.0,[Unknown],1,None,None,0::Unknown,1.0,0::20||1::22,0::Adult 18+||1::Adult 18+,0::Male||1::Male,NaN,"0::Unharmed, Arrested||1::Unharmed, Arrested",0::Subject-Suspect||1::Subject-Suspect
140224,1076607,2018-03-22,Wyoming,Glenrock,1,0,0.0,"[Unknown, Unknown]",2,None,None,0::Handgun||1::Rifle,2.0,0::86,0::Adult 18+,0::Male,NaN,0::Killed,0::Subject-Suspect
140225,1079998,2018-03-28,Wyoming,Jackson (Jackson Hole),0,0,0.0,[Stolen],None,1,None,0::Rifle,1.0,NaN,NaN,NaN,NaN,NaN,NaN